kind: SylvaWorkloadCluster
apiVersion: sylvaworkloadclusters.workloadclusteroperator.sylva/v1alpha1
metadata:
  name: swc
spec:
  k8sVersion: 1.27  # without minor
  # which parts of sylva-units `.cluster`
  infrastructure: openstack # metal3, vsphere
  controlPlane:
    provider: rke2 # kubeadm
    replicas: 3
  machineDeployments:  # mapped to sylva-units .cluster.machine_deployments
    # but not everything is allowed
    # in particular, no `{{.*}}` string is allowed
    my-md1-name:
      replicas: 1
    my-md2-name:
      replicas: 2
  enabledUnits:   # shortcut to have something lighter than sylvaUnitsValues.units.xxx.enabled
    multus: true # false
